# Generated by Django 6.0.2 on 2026-02-16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DayJournal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("session", models.CharField(default="NY", max_length=40)),
                ("symbol", models.CharField(blank=True, default="", max_length=20)),
                ("trade_taken", models.BooleanField(default=False)),
                ("why_taken", models.TextField(blank=True, default="")),
                ("what_i_did_well", models.TextField(blank=True, default="")),
                ("what_to_improve", models.TextField(blank=True, default="")),
                ("general_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="JournalSlotItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("D", "Daily"),
                            ("4H", "4H"),
                            ("1H", "1H"),
                            ("15M", "15M"),
                            ("5M", "5M"),
                            ("1M", "1M (Optional)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                (
                    "concept",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="journal.concept"),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_items",
                        to="journal.dayjournal",
                    ),
                ),
            ],
            options={"ordering": ["timeframe", "order"]},
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="journal.strategy",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("strategy", "name")},
            },
        ),
        migrations.CreateModel(
            name="SessionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("symbol", models.CharField(blank=True, default="", max_length=20)),
                ("day_notes", models.TextField(blank=True, default="")),
                ("trade_taken", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_runs",
                        to="journal.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="journal.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("section", "title")},
            },
        ),
        migrations.CreateModel(
            name="StepImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="step_images/")),
                ("caption", models.CharField(blank=True, default="", max_length=180)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="journal.step",
                    ),
                ),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="StepCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                (
                    "session_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_checks",
                        to="journal.sessionrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="journal.step",
                    ),
                ),
            ],
            options={
                "ordering": ["step__section__order", "step__order", "id"],
                "unique_together": {("session_run", "step")},
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5)),
                ("entry_time", models.DateTimeField()),
                ("stop", models.DecimalField(decimal_places=4, max_digits=12)),
                ("target", models.DecimalField(decimal_places=4, max_digits=12)),
                ("result_r", models.DecimalField(decimal_places=2, max_digits=8)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "session_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade",
                        to="journal.sessionrun",
                    ),
                ),
            ],
            options={"ordering": ["-entry_time"]},
        ),
    ]
